### ISSUE TITLE
what's the meaning of fraction of GPT4?

### ISSUE THREAD

**Issue by ljch2018** [openai/weak-to-strong#17]
<img width="1000" alt="image" src="https://github.com/openai/weak-to-strong/assets/22562546/f33c0f89-2099-47bd-a117-6b1e37026d10">
I read the original paper, but met some problems about the graph.

1. What's the meaning of fraction of GPT4 (X-axis) ?
2. Is one line stand for a different student model?  

Thank you very much.

**Comment by zidong-onepiece1** [comment]
1.The fraction of GPT4 (X-axis) may represents the size of the student model, '1' represents GPT4, 10^-2 represents GPT4 parameters * 0.01 and so on.
2. one line represents weak model conpute. The lighter the color, the greater the weak model conpute.

**Comment by WuTheFWasThat** [comment]
zidong is correct except that 10^(-2) doesn't necessarily mean parameters * 0.01, it means less parameters and trained for 0.01x the compute
