### ISSUE TITLE
Protect main branch and make changes through pull requests

### ISSUE THREAD

**Issue by EwoutH** [openai/weak-to-strong#6]
First of all, thanks a lot for making this open source. It's a really fascinating approach to solving superalignment!

Now that this project is open source, I would like to suggest to adopt some open source best-practices. One of these would be protecting the main branch, so no commits can be directly made to it. All changes will be made though pull requests.

This increased the stability and adds a layer of transparency and implicit documentation (with the PRs). It also allows anyone to view, review and ask questions about the changes.

For protecting the main branch, see the [GitHub docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule).

**Comment by WuTheFWasThat** [comment]
thanks for your interest!  i don't think there's much value in this as this is primarily a research codebase.  we're not likely to maintain this long run outside of addressing bugs/issues.  our expectation is that people might use it as a starting point for research projects but would fork it.  and in particular, we will definitely not ever give push access to non-openai employees

(also note that you can comment directly on commits as well)
